version: '3'
services:
  webserver:
    build: ./docker/node/
    container_name: application
    # tty: true
    command: ash -c "bin/www"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  db:
    build: ./docker/mysql/
    container_name: mysql
    tty: true
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  angular:
    build: ./docker/angular
    container_name: angular
    command: ash -c "ng serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "4200:4200"
